color0 #17130e
color1 #ffb4ab
color2 #ffb959
color3 #dec2a2
color4 #bacd9f
color5 #ffb959
color6 #dec2a2
color7 #ebe1d9
color8 #9c8e80
color9 #ffb4ab
color10 #ffb959
color11 #dec2a2
color12 #bacd9f
color13 #ffb959
color14 #dec2a2
color15 #ebe1d9

cursor                #ebe1d9
cursor_text_color     #17130e
background            #17130e
foreground            #ebe1d9
selection_foreground  #d3c4b4
selection_background  #4f4539
active_border_color   #ffb959
inactive_border_color #4f4539
url_color             #ffb959

active_tab_foreground   #462b00
active_tab_background   #ffb959
inactive_tab_foreground #d3c4b4
inactive_tab_background #4f4539
cursor_trail_color      #d3c4b4
