foreground #E5E8FB
background #0B0A1B
cursor #CBB3FB

color0   #040404
color1   #E21650
color2   #61c766
color3   #9680F0
color4   #413C8C
color5   #DA61EB
color6   #4C44C8
color7   #CBB3FB
color8   #AB9CFA
color9   #DC647C
color10  #70d675
color11  #ffe744
color12  #8769A5
color13  #5C546C
color14  #5cdff0
color15  #fdf6e3

selection_foreground #0B0A1B
selection_background #E5E8FB
